export const COURSES_FETCH_DATA = "COURSES_FETCH_DATA";
export const COURSES_REMOVE_DATA = "COURSES_REMOVE_DATA";
export const ADD_SUBJECT = "ADD_SUBJECT";
export const REMOVE_SUBJECT = "REMOVE_SUBJECT";
export const EDIT_SUBJECT_NAME = "EDIT_SUBJECT_NAME";
export const IMPORT_COURSES_CONFIG = "IMPORT_COURSES_CONFIG";
export const UPLOAD_COURSES_CONFIG = "UPLOAD_COURSES_CONFIG";
