export const ADD_SUBJECT = "ADD_SUBJECT";
export const REMOVE_SUBJECT = "REMOVE_SUBJECT";
export const EDIT_SUBJECT = "EDIT_SUBJECT";
export const IMPORT_COURSES_CONFIG = "IMPORT_COURSES_CONFIG";
export const UPLOAD_COURSES_CONFIG = "UPLOAD_COURSES_CONFIG";
