export const COURSES_FETCH_DATA = "COURSES_FETCH_DATA";
export const COURSES_REMOVE_DATA = "COURSES_REMOVE_DATA";
export const ADD_COURSE = "ADD_COURSE";
export const REMOVE_COURSE = "REMOVE_COURSE";
export const EDIT_COURSE = "EDIT_COURSE";
export const IMPORT_COURSES_CONFIG = "IMPORT_COURSES_CONFIG";
export const UPLOAD_COURSES_CONFIG = "UPLOAD_COURSES_CONFIG";
